# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
    default:
        - step:
            script:
                # add github remote and push all to keep it in sync
                - apt-get update
                - apt-get install -y --no-install-recommends git
                - git remote add github git@github.com:node-radic/console
                - git push github --all
                - git push github --tags

                # install yarn
                - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.18.1
                - export PATH=$HOME/.yarn/bin:$PATH

                # install dependencies and build the package
                - yarn install
                - npm run build

                # unit tests
                - npm run test

    branches:
        master:
            - step:
                script:
                    # install yarn
                    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.18.1
                    - export PATH=$HOME/.yarn/bin:$PATH

                    # run yarn install
                    - yarn install

                    # deploy typedoc
                    - npm run dev:docs
                    - npm run deploy:docs
    custom:
        deploy-ghpages-docs:
            - step:
                script:
                    - npm run dev:docs
                    - npm run deploy:docs