# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
    default:
        - step:
            script:
                - apt-get update
                - apt-get install -y --no-install-recommends git
                - git remote add github git@github.com:node-radic/rcli
                - git push github --all
                - git push github --tags
                - echo "Everything is awesome!"